# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/timing.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_10ge.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_1ge.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_10ge_port1.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_dram.xdc

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ten_gig_eth_pcs_pma/ten_gig_eth_pcs_pma.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma || ORIG_REF_NAME==ten_gig_eth_pcs_pma} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma/one_gig_eth_pcs_pma.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==one_gig_eth_pcs_pma || ORIG_REF_NAME==one_gig_eth_pcs_pma} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ddr3_32bit/ddr3_32bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr3_32bit || ORIG_REF_NAME==ddr3_32bit} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi64_4k_2clk_fifo/axi64_4k_2clk_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi64_4k_2clk_fifo || ORIG_REF_NAME==axi64_4k_2clk_fifo} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi64_8k_2clk_fifo/axi64_8k_2clk_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi64_8k_2clk_fifo || ORIG_REF_NAME==axi64_8k_2clk_fifo} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/bootram/bootram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bootram || ORIG_REF_NAME==bootram} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/bus_clk_gen/bus_clk_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bus_clk_gen || ORIG_REF_NAME==bus_clk_gen} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/fifo_4k_2clk/fifo_4k_2clk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_4k_2clk || ORIG_REF_NAME==fifo_4k_2clk} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/fifo_short_2clk/fifo_short_2clk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_short_2clk || ORIG_REF_NAME==fifo_short_2clk} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/pcie_clk_gen/pcie_clk_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_clk_gen || ORIG_REF_NAME==pcie_clk_gen} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/radio_clk_gen/radio_clk_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==radio_clk_gen || ORIG_REF_NAME==radio_clk_gen} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_fft/axi_fft.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_fft || ORIG_REF_NAME==axi_fft} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_hb31/axi_hb31.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_hb31 || ORIG_REF_NAME==axi_hb31} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_hb47/axi_hb47.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_hb47 || ORIG_REF_NAME==axi_hb47} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_to_magphase/complex_to_magphase.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==complex_to_magphase || ORIG_REF_NAME==complex_to_magphase} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_to_magphase_int16_int24/complex_to_magphase_int16_int24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==complex_to_magphase_int16_int24 || ORIG_REF_NAME==complex_to_magphase_int16_int24} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_to_magphase_int32/complex_to_magphase_int32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==complex_to_magphase_int32 || ORIG_REF_NAME==complex_to_magphase_int32} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_multiplier/complex_multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==complex_multiplier || ORIG_REF_NAME==complex_multiplier} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_multiplier_dds/complex_multiplier_dds.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==complex_multiplier_dds || ORIG_REF_NAME==complex_multiplier_dds} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotator/cordic_rotator.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_rotator || ORIG_REF_NAME==cordic_rotator} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotator24/cordic_rotator24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_rotator24 || ORIG_REF_NAME==cordic_rotator24} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotate_int24_int16/cordic_rotate_int24_int16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_rotate_int24_int16 || ORIG_REF_NAME==cordic_rotate_int24_int16} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotate_int24/cordic_rotate_int24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_rotate_int24 || ORIG_REF_NAME==cordic_rotate_int24} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int16/divide_int16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divide_int16 || ORIG_REF_NAME==divide_int16} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int24/divide_int24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divide_int24 || ORIG_REF_NAME==divide_int24} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int32/divide_int32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divide_int32 || ORIG_REF_NAME==divide_int32} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_uint32/divide_uint32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divide_uint32 || ORIG_REF_NAME==divide_uint32} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int16_int32/divide_int16_int32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divide_int16_int32 || ORIG_REF_NAME==divide_int16_int32} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/dds_sin_cos_lut_only/dds_sin_cos_lut_only.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_sin_cos_lut_only || ORIG_REF_NAME==dds_sin_cos_lut_only} -quiet] -quiet

# Block Designs: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/axi_intercon_2x64_128_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intercon_2x64_128_bd || ORIG_REF_NAME==axi_intercon_2x64_128_bd} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_width_conv_0/axi_intercon_2x64_128_bd_s00_width_conv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intercon_2x64_128_bd_s00_width_conv_0 || ORIG_REF_NAME==axi_intercon_2x64_128_bd_s00_width_conv_0} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_width_conv_0/axi_intercon_2x64_128_bd_s01_width_conv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intercon_2x64_128_bd_s01_width_conv_0 || ORIG_REF_NAME==axi_intercon_2x64_128_bd_s01_width_conv_0} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_xbar_0/axi_intercon_2x64_128_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intercon_2x64_128_bd_xbar_0 || ORIG_REF_NAME==axi_intercon_2x64_128_bd_xbar_0} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_m00_rs_0/axi_intercon_2x64_128_bd_m00_rs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intercon_2x64_128_bd_m00_rs_0 || ORIG_REF_NAME==axi_intercon_2x64_128_bd_m00_rs_0} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_rs_0_0/axi_intercon_2x64_128_bd_s01_rs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intercon_2x64_128_bd_s01_rs_0_0 || ORIG_REF_NAME==axi_intercon_2x64_128_bd_s01_rs_0_0} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_rs_0_0/axi_intercon_2x64_128_bd_s00_rs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intercon_2x64_128_bd_s00_rs_0_0 || ORIG_REF_NAME==axi_intercon_2x64_128_bd_s00_rs_0_0} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_rs_1_0/axi_intercon_2x64_128_bd_s00_rs_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intercon_2x64_128_bd_s00_rs_1_0 || ORIG_REF_NAME==axi_intercon_2x64_128_bd_s00_rs_1_0} -quiet] -quiet

# IP: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_rs_1_0/axi_intercon_2x64_128_bd_s01_rs_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intercon_2x64_128_bd_s01_rs_1_0 || ORIG_REF_NAME==axi_intercon_2x64_128_bd_s01_rs_1_0} -quiet] -quiet

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_width_conv_0/axi_intercon_2x64_128_bd_s00_width_conv_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intercon_2x64_128_bd_s00_width_conv_0 || ORIG_REF_NAME==axi_intercon_2x64_128_bd_s00_width_conv_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_width_conv_0/axi_intercon_2x64_128_bd_s00_width_conv_0_ooc.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_width_conv_0/axi_intercon_2x64_128_bd_s01_width_conv_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_intercon_2x64_128_bd_s01_width_conv_0 || ORIG_REF_NAME==axi_intercon_2x64_128_bd_s01_width_conv_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_width_conv_0/axi_intercon_2x64_128_bd_s01_width_conv_0_ooc.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_xbar_0/axi_intercon_2x64_128_bd_xbar_0_ooc.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_m00_rs_0/axi_intercon_2x64_128_bd_m00_rs_0_ooc.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_rs_0_0/axi_intercon_2x64_128_bd_s01_rs_0_0_ooc.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_rs_0_0/axi_intercon_2x64_128_bd_s00_rs_0_0_ooc.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_rs_1_0/axi_intercon_2x64_128_bd_s00_rs_1_0_ooc.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_rs_1_0/axi_intercon_2x64_128_bd_s01_rs_1_0_ooc.xdc

# XDC: /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/axi_intercon_2x64_128_bd_ooc.xdc
