# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
create_project -in_memory -part xc7k410tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/vivado/rfnoc/src/rfnoc-kwan_cross/xilinx-fpga-project/2wire/2wire.cache/wt [current_project]
set_property parent.project_path /home/vivado/rfnoc/src/rfnoc-kwan_cross/xilinx-fpga-project/2wire/2wire.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/vivado/rfnoc/src/rfnoc-kwan_cross/xilinx-fpga-project/2wire/2wire.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property verilog_define {BUILD_1G=1 BUILD_10G=1 SFP0_1GBE=1 SFP1_10GBE=1 RFNOC=1 X310=1 GIT_HASH=32'hf1b40696} [current_fileset]
add_files /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/bootram/bootram.coe
read_verilog {
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/radio/radio_core_regs.vh
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_shell_regs.vh
}
read_verilog -library xil_defaultlib {
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_pcie_int.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_core.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_sfpp_io_core.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_db_fe_core.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/soft_ctrl.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/capture_ddrlvds.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/gen_ddrlvds.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/bus_int.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_demux4.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_demux8.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_demux.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_fifo_2clk.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_fifo32_to_fifo64.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_fifo64_to_fifo32.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_fifo_bram.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_fifo_cascade.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_fifo_flop2.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_fifo_flop.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_fifo_short.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_filter_mux4.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_loopback.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_mux4.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_mux8.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_mux_select.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_mux.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/axi_packet_gate.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/fifo64_to_axi4lite.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/monitor_axi_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/fifo/shortfifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/ad5662_auto_spi.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/arb_qualify_master.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/axi_crossbar.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/axi_crossbar_regport.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/axi_fifo_header.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/axi_forwarding_cam.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/axi_setting_reg.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/axi_slave_mux.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/axi_test_vfifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/bin2gray.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/binary_encoder.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/filter_bad_sid.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/gpio_atr_io.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/gpio_atr.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/gray2bin.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/por_gen.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/priority_encoder_one_hot.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/priority_encoder.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/radio_ctrl_proc.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/ram_2port.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/reset_sync.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/s7_icap_wb.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/serial_to_settings.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/setting_reg.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/settings_bus_mux.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/settings_bus_timed_2clk.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/simple_i2c_core.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/simple_spi_core.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/synchronizer_impl.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/synchronizer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/pulse_synchronizer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/user_settings.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/axil_regport_master.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/axil_to_ni_regport.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/regport_resp_mux.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/regport_to_xbar_settingsbus.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/regport_to_settingsbus.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/pulse_stretch.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/mdio_master.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/map/cam_priority_encoder.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/map/cam_bram.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/map/cam_srl.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/map/cam.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/map/kv_map.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/control/map/axis_muxed_kv_map.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/simple_gemac_wrapper.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/simple_gemac.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/simple_gemac_tx.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/simple_gemac_rx.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/crc.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/delay_line.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/flow_ctrl_tx.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/flow_ctrl_rx.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/address_filter.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/address_filter_promisc.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/ll8_to_txmac.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/rxmac_to_ll8.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/ll8_to_axi64.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/axi64_to_ll8.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/gmii_to_axis.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/simple_gemac/mdio.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/timing/time_compare.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/timing/timekeeper.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/timing/pps_generator.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/timing/pps_synchronizer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbdec1.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbdec2.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbdec3.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbint1.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbint2.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbint3.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/zpu/zpu_bootram.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/wishbone/simple_uart_rx.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/wishbone/simple_uart_tx.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/wishbone/simple_uart.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/wishbone/wb_1master.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/wishbone/settings_bus.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/wishbone/settings_readback.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/wishbone/i2c_master_top.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/wishbone/i2c_master_bit_ctrl.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/wishbone/i2c_master_byte_ctrl.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/wishbone/axi_stream_to_wb.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/fault_sm.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/generic_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/generic_fifo_ctrl.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/generic_mem_xilinx_block.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/generic_mem_medium.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/generic_mem_small.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/meta_sync.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/meta_sync_single.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/rx_checker.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/rx_data_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/rx_dequeue.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/rx_enqueue.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/rx_hold_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/sync_clk_core.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/sync_clk_wb.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/sync_clk_xgmii_tx.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/tx_checker.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/tx_data_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/tx_dequeue.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/tx_enqueue.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/tx_hold_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/wishbone_if.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/xge_mac.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge/rtl/verilog/xge_mac_wb.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge_interface/axi64_to_xge64.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge_interface/axi_count_packets_in_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge_interface/xge64_to_axi64.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge_interface/xge_handshake.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/xge_interface/xge_mac_wrapper.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/ip/ten_gig_eth_pcs_pma/ten_gige_phy_clk_gen.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/ip/ten_gig_eth_pcs_pma/ten_gige_phy.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ten_gig_eth_pcs_pma_ex/imports/ten_gig_eth_pcs_pma_example_design.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ten_gig_eth_pcs_pma_ex/imports/ten_gig_eth_pcs_pma_ff_synchronizer_rst2.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ten_gig_eth_pcs_pma_ex/imports/ten_gig_eth_pcs_pma_gt_common.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ten_gig_eth_pcs_pma_ex/imports/ten_gig_eth_pcs_pma_shared_clock_and_reset.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ten_gig_eth_pcs_pma_ex/imports/ten_gig_eth_pcs_pma_support.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/ip/one_gig_eth_pcs_pma/one_gige_phy_clk_gen.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/ip/one_gig_eth_pcs_pma/one_gige_phy.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma_ex/imports/one_gig_eth_pcs_pma_example_design.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma_ex/imports/one_gig_eth_pcs_pma_reset_sync_ex.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma_ex/imports/one_gig_eth_pcs_pma_sync_block_ex.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma_ex/imports/one_gig_eth_pcs_pma_tx_elastic_buffer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma_ex/imports/one_gig_eth_pcs_pma_clocking.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma_ex/imports/one_gig_eth_pcs_pma_gt_common.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma_ex/imports/one_gig_eth_pcs_pma_resets.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma_ex/imports/one_gig_eth_pcs_pma_support.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_port2/LvFpga_Chinch_Interface.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_port2/ioport2_msg_codec.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_port2/pcie_pkt_route_specifier.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_port2/pcie_axi_wb_conv.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_port2/pcie_wb_reg_core.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_port2/pcie_iop2_msg_arbiter.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_port2/pcie_basic_regs.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_port2/pcie_dma_ctrl.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_port2/data_swapper_64.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_port2/pcie_lossy_samp_gate.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/axis_packet_debug.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/chdr_eth_framer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/cvita_chunker.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/cvita_dechunker.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/cvita_dest_lookup.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/cvita_insert_tlast.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/cvita_packet_debug.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/eth_dispatch.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/eth_interface.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/fix_short_packet.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/ip_hdr_checksum.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/source_flow_control.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/vita_eth_framer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/packet_proc/arm_deframer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/vita/flow_control_responder.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/vita/packet_error_responder.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/acc.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/add2_and_clip_reg.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/add2_and_clip.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/add2_and_round_reg.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/add2_and_round.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/add2_reg.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/add2.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/add_then_mac.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/cic_decim.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/cic_dec_shifter.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/cic_interp.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/cic_int_shifter.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/cic_strober.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/clip_reg.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/clip.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/cordic_stage.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/cordic_z24.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/ddc_chain.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/duc_chain.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/hb47_int.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/hb_dec.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/hb_interp.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/round_reg.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/round_sd.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/round.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/rx_dcoffset.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/rx_frontend.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/sign_extend.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/small_hb_dec.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/small_hb_int.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/srl.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/dsp/tx_frontend.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ddr3_32bit/ddr3_32bit/user_design/rtl/clocking/mig_7series_v4_0_tempmon.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_chdr_header_trigger.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_chdr_test_pattern.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_defs.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_dma_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_dma_master.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_replay.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_embed_tlast.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_extract_tlast.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_fast_extract_tlast.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_fast_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_to_strobed.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_dummy.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/strobed_to_axi.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_add_preamble.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/axi_strip_preamble.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/axi/crc_xnor.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/radio/radio_datapath_core.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/radio/db_control.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/radio/rx_frontend_gen3.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/radio/tx_frontend_gen3.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/radio/rx_control_gen3.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/radio/tx_control_gen3.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/radio/noc_block_radio_core.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_cap_gen/cap_pattern_verifier.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/axi_intercon_2x64_128_bd_wrapper.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/cmd_pkt_proc.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/chdr_fifo_large.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/chdr_framer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/chdr_framer_2clk.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/chdr_deframer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/chdr_deframer_2clk.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_shell.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_packet_mux.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_wrapper.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_bit_reduce.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_axi_fifo_loopback.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_axi_dma_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_replay.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_fir_filter.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_fft.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_null_source_sink.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_schmidl_cox.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_packet_resizer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_split_stream.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_vector_iir.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_addsub.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_window.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_keep_one_in_n.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_pfb.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_export_io.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_conv_encoder_qpsk.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_siggen.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_digital_gain.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_debug.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/pfb.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/pfb_stage.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/null_source.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/schmidl_cox.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/split_stream.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/split_stream_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/conj.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/delay_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/delay_type2.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/delay_type3.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/delay_type4.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/complex_to_magsq.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/phase_accum.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/complex_invert.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/periodic_framer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/threshold_scaled.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/moving_sum.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/peak_finder.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/window.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/counter.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/puncture.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/symbol_to_gray_bits.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/ram_to_fifo.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/const.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/const_sreg.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/cmul.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/cadd.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_input_port.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_output_port.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_responder.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/keep_one_in_n.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/vector_iir.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/addsub.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/packet_resizer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_pipe.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/multiply.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/mult.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/mult_add.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/mult_rc.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/mult_add_rc.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fft_shift.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_pipe_join.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_pipe_mac.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_round_and_clip_complex.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_round_complex.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_clip_complex.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_join.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_sync.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/split_complex.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_round_and_clip.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/join_complex.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_round.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_clip.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_clip_unsigned.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_serializer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_deserializer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_throttle.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_packer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/complex_to_mag_approx.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_file_source.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_file_io.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/file_source.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/file_sink.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/ofdm_plateau_detector.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/ofdm_peak_detector.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/delay.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/fifo_srl.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/rng.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/f15_avg.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/f15_binmap.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/f15_core.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/f15_eoseq.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/f15_histo_mem.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/f15_line_mem.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/f15_logpwr.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/f15_maxhold.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/f15_packetizer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/f15_rise_decay.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/f15_wf_agg.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fosphor/axi_logpwr.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_logpwr.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_fosphor.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_moving_avg.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/ofdm_constellation_demapper.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_ofdm_constellation_demapper.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/one_tap_equalizer.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_eq.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_ddc.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/noc_block_duc.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/cvita_hdr_parser.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/cvita_hdr_encoder.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/cvita_hdr_decoder.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/cvita_hdr_modify.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_async_stream.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_rate_change.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_tag_time.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_drop_partial_packet.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/cordic.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/cordic_timed.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/ddc.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/duc.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/cic_decimate.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/cic_interpolate.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/sine_tone.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/axi_fir_filter.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/fir_filter_slice.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/dds_freq_tune.v
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/dds_timed.v
  /home/vivado/rfnoc/src/rfnoc-kwan_cross/rfnoc/fpga-src/noc_block_Latencytest.v
}
read_vhdl -library work {
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_zpu_config.vhd
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/zpu/zpu_top_pkg.vhd
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/zpu/zpu_wb_top.vhd
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/zpu/wishbone/wishbone_pkg.vhd
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/zpu/wishbone/zpu_system.vhd
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/zpu/wishbone/zpu_wb_bridge.vhd
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/zpu/core/zpu_core.vhd
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/zpu/core/zpupkg.vhd
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/radio/WrapBufg.vhd
  /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/rfnoc/addsub.vhd
}
read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ten_gig_eth_pcs_pma/ten_gig_eth_pcs_pma.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ten_gig_eth_pcs_pma/synth/ten_gig_eth_pcs_pma_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ten_gig_eth_pcs_pma/synth/ten_gig_eth_pcs_pma_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ten_gig_eth_pcs_pma/synth/ten_gig_eth_pcs_pma.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma/one_gig_eth_pcs_pma.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma/one_gig_eth_pcs_pma_board.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma/synth/one_gig_eth_pcs_pma.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/one_gig_eth_pcs_pma/synth/one_gig_eth_pcs_pma_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ddr3_32bit/ddr3_32bit.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ddr3_32bit/ddr3_32bit/user_design/constraints/ddr3_32bit.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/ddr3_32bit/ddr3_32bit/user_design/constraints/ddr3_32bit_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi64_4k_2clk_fifo/axi64_4k_2clk_fifo.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi64_4k_2clk_fifo/axi64_4k_2clk_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi64_4k_2clk_fifo/axi64_4k_2clk_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi64_4k_2clk_fifo/axi64_4k_2clk_fifo_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi64_8k_2clk_fifo/axi64_8k_2clk_fifo.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi64_8k_2clk_fifo/axi64_8k_2clk_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi64_8k_2clk_fifo/axi64_8k_2clk_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi64_8k_2clk_fifo/axi64_8k_2clk_fifo_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/bootram/bootram.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/bootram/bootram_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/bus_clk_gen/bus_clk_gen.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/bus_clk_gen/bus_clk_gen_board.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/bus_clk_gen/bus_clk_gen.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/bus_clk_gen/bus_clk_gen_late.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/bus_clk_gen/bus_clk_gen_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/fifo_4k_2clk/fifo_4k_2clk.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/fifo_4k_2clk/fifo_4k_2clk.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/fifo_4k_2clk/fifo_4k_2clk_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/fifo_4k_2clk/fifo_4k_2clk_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/fifo_short_2clk/fifo_short_2clk.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/fifo_short_2clk/fifo_short_2clk.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/fifo_short_2clk/fifo_short_2clk_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/fifo_short_2clk/fifo_short_2clk_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/pcie_clk_gen/pcie_clk_gen.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/pcie_clk_gen/pcie_clk_gen_board.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/pcie_clk_gen/pcie_clk_gen.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/pcie_clk_gen/pcie_clk_gen_late.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/pcie_clk_gen/pcie_clk_gen_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/radio_clk_gen/radio_clk_gen.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/radio_clk_gen/radio_clk_gen_board.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/radio_clk_gen/radio_clk_gen.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/radio_clk_gen/radio_clk_gen_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_fft/axi_fft.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_fft/axi_fft_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_hb31/axi_hb31.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_hb31/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_hb31/axi_hb31_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_hb47/axi_hb47.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_hb47/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_hb47/axi_hb47_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_to_magphase/complex_to_magphase.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_to_magphase/complex_to_magphase_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_to_magphase_int16_int24/complex_to_magphase_int16_int24.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_to_magphase_int16_int24/complex_to_magphase_int16_int24_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_to_magphase_int32/complex_to_magphase_int32.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_to_magphase_int32/complex_to_magphase_int32_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_multiplier/complex_multiplier.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_multiplier/complex_multiplier_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_multiplier_dds/complex_multiplier_dds.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/complex_multiplier_dds/complex_multiplier_dds_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotator/cordic_rotator.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotator/cordic_rotator_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotator24/cordic_rotator24.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotator24/cordic_rotator24_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotate_int24_int16/cordic_rotate_int24_int16.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotate_int24_int16/cordic_rotate_int24_int16_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotate_int24/cordic_rotate_int24.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/cordic_rotate_int24/cordic_rotate_int24_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int16/divide_int16.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int16/divide_int16_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int24/divide_int24.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int24/divide_int24_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int32/divide_int32.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int32/divide_int32_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_uint32/divide_uint32.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_uint32/divide_uint32_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int16_int32/divide_int16_int32.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/divide_int16_int32/divide_int16_int32_ooc.xdc]

read_ip -quiet /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/dds_sin_cos_lut_only/dds_sin_cos_lut_only.xci
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/dds_sin_cos_lut_only/dds_sin_cos_lut_only_ooc.xdc]

add_files /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/axi_intercon_2x64_128_bd.bd
set_property used_in_synthesis false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_width_conv_0/axi_intercon_2x64_128_bd_s00_width_conv_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_width_conv_0/axi_intercon_2x64_128_bd_s00_width_conv_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_width_conv_0/axi_intercon_2x64_128_bd_s00_width_conv_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_width_conv_0/axi_intercon_2x64_128_bd_s01_width_conv_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_width_conv_0/axi_intercon_2x64_128_bd_s01_width_conv_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_width_conv_0/axi_intercon_2x64_128_bd_s01_width_conv_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_xbar_0/axi_intercon_2x64_128_bd_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_m00_rs_0/axi_intercon_2x64_128_bd_m00_rs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_rs_0_0/axi_intercon_2x64_128_bd_s01_rs_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_rs_0_0/axi_intercon_2x64_128_bd_s00_rs_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s00_rs_1_0/axi_intercon_2x64_128_bd_s00_rs_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/ip/axi_intercon_2x64_128_bd_s01_rs_1_0/axi_intercon_2x64_128_bd_s01_rs_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/build-ip/xc7k410tffg900-2/axi_intercon_2x64_128_bd/axi_intercon_2x64_128_bd_ooc.xdc]

read_edif /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbdec1.ngc
read_edif /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbdec2.ngc
read_edif /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbdec3.ngc
read_edif /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbint1.ngc
read_edif /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbint2.ngc
read_edif /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/coregen_dsp/hbint3.ngc
read_edif /home/vivado/rfnoc/src/uhd-fpga/usrp3/lib/io_port2/LvFpga_Chinch_Interface.ngc
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300.xdc
set_property used_in_implementation false [get_files /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300.xdc]

read_xdc /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/timing.xdc
set_property used_in_implementation false [get_files /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/timing.xdc]

read_xdc /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_10ge.xdc
set_property used_in_implementation false [get_files /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_10ge.xdc]

read_xdc /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_1ge.xdc
set_property used_in_implementation false [get_files /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_1ge.xdc]

read_xdc /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_10ge_port1.xdc
set_property used_in_implementation false [get_files /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_10ge_port1.xdc]

read_xdc /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_dram.xdc
set_property used_in_implementation false [get_files /home/vivado/rfnoc/src/uhd-fpga/usrp3/top/x300/x300_dram.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top x300 -part xc7k410tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef x300.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file x300_utilization_synth.rpt -pb x300_utilization_synth.pb"
